# -*- coding: utf-8 -*-
"""ControlCyber Launcher

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e4VTLiHmmxkzfswZFPbpS3CQ2yuABJnG
"""

# LAUNCHER V1.1
# Usando Mutex nativo con monitoreo directo .wait usando ctypes
# ==============================================================================
import os
import sys
import time
import subprocess
import ctypes
from ctypes import wintypes

# ==============================================================================
# CONTROL DE INSTANCIAS ROBUSTO (MUTEX NATIVO)
# ==============================================================================
ERROR_ALREADY_EXISTS = 183

# Definir las funciones de la API de Windows de forma segura
kernel32 = ctypes.WinDLL('kernel32', use_last_error=True)
CreateMutex = kernel32.CreateMutexW
CreateMutex.argtypes = [wintypes.LPCVOID, wintypes.BOOL, wintypes.LPCWSTR]
CreateMutex.restype = wintypes.HANDLE

# Este nombre DEBE coincidir exactamente con el que pusiste en AppMutex de Inno Setup
MUTEX_NAME = "ControlLauncherMutexSecret"

# Intentar crear el Mutex en la memoria de Windows
mutex_handle = CreateMutex(None, False, MUTEX_NAME)
last_error = kernel32.GetLastError()

if last_error == ERROR_ALREADY_EXISTS:
    # Si el Mutex ya existe, entonces YA HAY un launcher ejecutándose.
    # Cerrar esta segunda instancia silenciosamente de inmediato.
    sys.exit(0)


# ==============================================================================
# LÓGICA DEL WATCHDOG (OPTIMIZADA A 0% DE CPU)
# ==============================================================================
APP_NAME = "cliente.exe"

def get_base_dir():
    if getattr(sys, "frozen", False):
        return os.path.dirname(sys.executable)
    return os.path.dirname(os.path.abspath(__file__))

BASE_DIR = get_base_dir()
CLIENTE = os.path.join(BASE_DIR, APP_NAME)

while True:
    try:
        if os.path.exists(CLIENTE):
            # Lanzamos el cliente y guardamos la referencia del proceso
            proceso_cliente = subprocess.Popen(CLIENTE)

            # .wait() congela este script de forma pasiva sin consumir CPU.
            # Windows le avisará al launcher en la millonésima de segundo exacta
            # en la que 'cliente.exe' muera o sea cerrado.
            proceso_cliente.wait()
        else:
            print(f"Error: No se encontró el ejecutable en {CLIENTE}")
            time.sleep(5) # Esperar un momento si el archivo desapareció temporalmente

    except Exception as e:
        # Evitar que el launcher colapse por algún error imprevisto
        time.sleep(2)